//! Main HTML generator for semantic tree visualization
//!
//! Contains the primary `generate_semantic_html` function and supporting types.

use bsl_shared::ir::SemanticProgram;

use super::renderers::{render_nodes, render_symbol_table};
use super::styles::{generate_inline_css, ColorScheme};
use super::utils::escape_html;

/// Backward compatible re-export of Theme from shared
///
/// Используйте `bsl_shared::formatting::Theme` напрямую для нового кода.
#[deprecated(since = "0.5.0", note = "Use bsl_shared::formatting::Theme instead")]
pub use bsl_shared::formatting::Theme;

/// Compact rendering mode
#[derive(Debug, Clone, Copy)]
pub struct RenderOptions {
    pub theme: Theme,
    pub compact: bool,
}

impl Default for RenderOptions {
    fn default() -> Self {
        Self {
            theme: Theme::Dark,
            compact: false,
        }
    }
}

/// Generates self-contained HTML with inline CSS for semantic tree visualization
///
/// # Arguments
/// * `program` - The semantic program to visualize
/// * `file_path` - Path to the BSL file being visualized
/// * `options` - Rendering options (theme, compact mode)
///
/// # Returns
/// Complete HTML document as a String
///
/// # Example
/// ```ignore
/// let html = generate_semantic_html(&program, "test.bsl", RenderOptions::default());
/// ```
pub fn generate_semantic_html(
    program: &SemanticProgram,
    file_path: &str,
    options: RenderOptions,
) -> String {
    let (colors, text_class) = match options.theme {
        Theme::Dark => (ColorScheme::dark(), "text-white"),
        Theme::Light => (ColorScheme::light(), "text-gray-900"),
    };

    let css_styles = generate_inline_css(&colors);

    let nodes_html = if program.nodes.is_empty() {
        "<div class=\"info-block\">No nodes found in semantic tree</div>".to_string()
    } else {
        render_nodes(&program.nodes, &colors, options.compact)
    };

    let symbol_table_html = render_symbol_table(&program.symbols);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Semantic Tree: {file_path}</title>
    <style>
{css_styles}
    </style>
</head>
<body class="{bg_class} {text_class}">
    <div class="container">
        <header>
            <h1>Semantic Tree Visualization</h1>
            <p class="subtitle">File: <code>{file_path}</code></p>
            <div class="meta-info">
                <span>Nodes: <strong>{node_count}</strong></span>
                <span>Theme: <strong>{theme_name}</strong></span>
            </div>
        </header>

        <main>
            <section class="section">
                <h2>Semantic Nodes ({node_count})</h2>
                <div class="nodes-container">
                    {nodes_html}
                </div>
            </section>

            <section class="section">
                <h2>Symbol Table</h2>
                <div class="symbol-table-container">
                    {symbol_table_html}
                </div>
            </section>

            <section class="section info-block">
                <h3>About This View</h3>
                <p>
                    This is a semantic tree visualization of your BSL program structure.
                    It shows all procedures, functions, variables, and their types as resolved
                    by the gradual type system.
                </p>
                <ul>
                    <li><strong>Procedures</strong> - All procedure declarations</li>
                    <li><strong>Functions</strong> - All function declarations with return types</li>
                    <li><strong>Variables</strong> - All variable declarations in symbol table</li>
                    <li><strong>Assignments</strong> - Type assignments and modifications</li>
                </ul>
            </section>
        </main>

        <footer>
            <p>Generated by BSL Gradual Type System - Powered by Tree-sitter</p>
        </footer>
    </div>
</body>
</html>"#,
        file_path = escape_html(file_path),
        bg_class = match options.theme {
            Theme::Dark => "bg-gray-900",
            Theme::Light => "bg-white",
        },
        node_count = program.nodes.len(),
        theme_name = match options.theme {
            Theme::Dark => "Dark",
            Theme::Light => "Light",
        },
        nodes_html = nodes_html,
        symbol_table_html = symbol_table_html,
        css_styles = css_styles,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use bsl_shared::ir::{SemanticProgram, SymbolTable};

    #[test]
    fn test_generate_dark_theme() {
        let program = SemanticProgram {
            symbols: SymbolTable::new(),
            nodes: vec![],
            source_info: bsl_shared::ir::SourceInfo {
                path: "test.bsl".to_string(),
                content_hash: 0,
            },
            cfg: None,
        };
        let html = generate_semantic_html(
            &program,
            "test.bsl",
            RenderOptions {
                theme: Theme::Dark,
                compact: false,
            },
        );
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("bg-gray-900"));
        assert!(html.contains("Semantic Tree Visualization"));
    }

    #[test]
    fn test_generate_light_theme() {
        let program = SemanticProgram {
            symbols: SymbolTable::new(),
            nodes: vec![],
            source_info: bsl_shared::ir::SourceInfo {
                path: "test.bsl".to_string(),
                content_hash: 0,
            },
            cfg: None,
        };
        let html = generate_semantic_html(
            &program,
            "test.bsl",
            RenderOptions {
                theme: Theme::Light,
                compact: false,
            },
        );
        assert!(html.contains("bg-white"));
        assert!(html.contains("Semantic Tree Visualization"));
    }
}
