# Конфигурация для GitHub Dependency Review

# Уровни угроз которые блокируют PR
fail-on-severity: moderate

# Лицензии которые запрещены
deny-licenses:
  - GPL-3.0
  - AGPL-3.0
  - LGPL-3.0

# Лицензии которые разрешены
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unicode-DFS-2016

# Исключения для определенных пакетов
allow-dependencies-licenses:
  - package-name: "some-package"
    licenses: ["GPL-3.0"]
    justification: "Required for tree-sitter functionality"

# Блокировать известные уязвимые пакеты
deny-packages:
  - package-name: "openssl"
    versions: ["< 1.1.1"]
    justification: "Known security vulnerabilities"

# Настройки комментариев в PR
comment-summary-in-pr: always
warn-only: false