id = "bsl-gradual-types"
name = "BSL (gradual types)"
version = "0.2.5"
schema_version = 1
authors = ["BSL Type System Team"]
description = "BSL support"
repository = "https://github.com/defin85/bsl-gradual-types"
languages = ["languages/bsl"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.bsl]
repository = "https://github.com/defin85/bsl-gradual-types"
rev = "3a546c2e63d49a397c0ba740fbe1a2a0757c46a7"
path = "third_party/tree-sitter-bsl"

[language_servers.bsl]
name = "BSL Language Server"
languages = ["BSL"]
