//! Semantic HTML Generator - Pure HTML visualization for BSL semantic trees
//!
//! Generates self-contained HTML with inline CSS for displaying semantic program structures.
//! Uses inline CSS only (no CDN) due to VSCode Content Security Policy restrictions.

use bsl_shared::ir::{SemanticProgram, SemanticNodeKind};

/// Theme for HTML visualization
#[derive(Debug, Clone, Copy)]
pub enum Theme {
    Dark,
    Light,
}

/// Compact rendering mode
#[derive(Debug, Clone, Copy)]
pub struct RenderOptions {
    pub theme: Theme,
    pub compact: bool,
}

impl Default for RenderOptions {
    fn default() -> Self {
        Self {
            theme: Theme::Dark,
            compact: false,
        }
    }
}

/// Generates self-contained HTML with inline CSS for semantic tree visualization
///
/// # Arguments
/// * `program` - The semantic program to visualize
/// * `file_path` - Path to the BSL file being visualized
/// * `options` - Rendering options (theme, compact mode)
///
/// # Returns
/// Complete HTML document as a String
///
/// # Example
/// ```ignore
/// let html = generate_semantic_html(&program, "test.bsl", RenderOptions::default());
/// ```
pub fn generate_semantic_html(
    program: &SemanticProgram,
    file_path: &str,
    options: RenderOptions,
) -> String {
    let (colors, text_class) = match options.theme {
        Theme::Dark => (ColorScheme::dark(), "text-white"),
        Theme::Light => (ColorScheme::light(), "text-gray-900"),
    };

    let css_styles = generate_inline_css(&colors);

    let nodes_html = if program.nodes.is_empty() {
        "<div class=\"info-block\">❌ No nodes found in semantic tree</div>".to_string()
    } else {
        render_nodes(&program.nodes, &colors, options.compact)
    };

    let symbol_table_html = render_symbol_table(&program.symbols);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Semantic Tree: {file_path}</title>
    <style>
{css_styles}
    </style>
</head>
<body class="{bg_class} {text_class}">
    <div class="container">
        <header>
            <h1>📊 Semantic Tree Visualization</h1>
            <p class="subtitle">File: <code>{file_path}</code></p>
            <div class="meta-info">
                <span>📈 Nodes: <strong>{node_count}</strong></span>
                <span>🎨 Theme: <strong>{theme_name}</strong></span>
            </div>
        </header>

        <main>
            <section class="section">
                <h2>🔍 Semantic Nodes ({node_count})</h2>
                <div class="nodes-container">
                    {nodes_html}
                </div>
            </section>

            <section class="section">
                <h2>📋 Symbol Table</h2>
                <div class="symbol-table-container">
                    {symbol_table_html}
                </div>
            </section>

            <section class="section info-block">
                <h3>ℹ️ About This View</h3>
                <p>
                    This is a semantic tree visualization of your BSL program structure.
                    It shows all procedures, functions, variables, and their types as resolved
                    by the gradual type system.
                </p>
                <ul>
                    <li><strong>Procedures (🔵)</strong> - All procedure declarations</li>
                    <li><strong>Functions (⚙️)</strong> - All function declarations with return types</li>
                    <li><strong>Variables (📌)</strong> - All variable declarations in symbol table</li>
                    <li><strong>Assignments (✏️)</strong> - Type assignments and modifications</li>
                </ul>
            </section>
        </main>

        <footer>
            <p>Generated by BSL Gradual Type System • Powered by Tree-sitter</p>
        </footer>
    </div>
</body>
</html>"#,
        file_path = escape_html(file_path),
        bg_class = match options.theme {
            Theme::Dark => "bg-gray-900",
            Theme::Light => "bg-white",
        },
        node_count = program.nodes.len(),
        theme_name = match options.theme {
            Theme::Dark => "Dark",
            Theme::Light => "Light",
        },
        nodes_html = nodes_html,
        symbol_table_html = symbol_table_html,
        css_styles = css_styles,
    )
}

/// Color scheme for different themes
struct ColorScheme {
    bg_primary: &'static str,
    bg_secondary: &'static str,
    text_primary: &'static str,
    text_secondary: &'static str,
    border_color: &'static str,
    accent_procedure: &'static str,
    accent_function: &'static str,
    accent_variable: &'static str,
    accent_assignment: &'static str,
    code_bg: &'static str,
}

impl ColorScheme {
    fn dark() -> Self {
        Self {
            bg_primary: "#111827",
            bg_secondary: "#1f2937",
            text_primary: "#f3f4f6",
            text_secondary: "#d1d5db",
            border_color: "#374151",
            accent_procedure: "#60a5fa",
            accent_function: "#34d399",
            accent_variable: "#fbbf24",
            accent_assignment: "#c084fc",
            code_bg: "#0f172a",
        }
    }

    fn light() -> Self {
        Self {
            bg_primary: "#ffffff",
            bg_secondary: "#f9fafb",
            text_primary: "#111827",
            text_secondary: "#6b7280",
            border_color: "#e5e7eb",
            accent_procedure: "#2563eb",
            accent_function: "#059669",
            accent_variable: "#d97706",
            accent_assignment: "#7c3aed",
            code_bg: "#f3f4f6",
        }
    }
}

/// Generates inline CSS styles
fn generate_inline_css(colors: &ColorScheme) -> String {
    format!(
        r#"        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            background-color: {bg_primary};
            color: {text_primary};
            font-family: 'Segoe UI', 'Consolas', 'Monaco', 'Courier New', monospace;
            line-height: 1.6;
            font-size: 14px;
        }}

        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }}

        header {{
            background-color: {bg_secondary};
            border-bottom: 2px solid {border_color};
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}

        h1 {{
            font-size: 28px;
            margin-bottom: 10px;
            font-weight: 700;
        }}

        h2 {{
            font-size: 22px;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid {border_color};
            font-weight: 600;
        }}

        h3 {{
            font-size: 18px;
            margin-bottom: 10px;
            font-weight: 600;
        }}

        .subtitle {{
            color: {text_secondary};
            font-size: 14px;
            margin-bottom: 15px;
        }}

        .meta-info {{
            display: flex;
            gap: 20px;
            margin-top: 15px;
            flex-wrap: wrap;
        }}

        .meta-info span {{
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 8px 12px;
            background-color: {bg_primary};
            border-radius: 4px;
            font-size: 13px;
        }}

        main {{
            display: flex;
            flex-direction: column;
            gap: 30px;
        }}

        .section {{
            background-color: {bg_secondary};
            border: 1px solid {border_color};
            padding: 20px;
            border-radius: 8px;
        }}

        .nodes-container,
        .symbol-table-container {{
            display: grid;
            grid-auto-flow: row;
            gap: 12px;
        }}

        .node {{
            background-color: {bg_primary};
            border-left: 4px solid;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 8px;
        }}

        .node-procedure {{
            border-left-color: {accent_procedure};
        }}

        .node-function {{
            border-left-color: {accent_function};
        }}

        .node-variable {{
            border-left-color: {accent_variable};
        }}

        .node-assignment {{
            border-left-color: {accent_assignment};
        }}

        .node-header {{
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 8px;
            font-weight: 600;
        }}

        .node-kind {{
            font-size: 12px;
            padding: 4px 8px;
            border-radius: 3px;
            background-color: {code_bg};
            color: {text_secondary};
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        .node-name {{
            font-size: 14px;
            font-weight: 700;
            font-family: 'Consolas', 'Monaco', monospace;
            color: {text_primary};
        }}

        .node-details {{
            margin-top: 10px;
            padding-top: 10px;
            border-top: 1px solid {border_color};
            font-size: 13px;
        }}

        .detail-line {{
            display: flex;
            gap: 15px;
            margin-bottom: 5px;
        }}

        .detail-label {{
            font-weight: 600;
            color: {text_secondary};
            min-width: 100px;
        }}

        .detail-value {{
            color: {text_primary};
            font-family: 'Consolas', 'Monaco', monospace;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}

        th {{
            background-color: {bg_primary};
            padding: 12px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid {border_color};
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        td {{
            padding: 12px;
            border-bottom: 1px solid {border_color};
        }}

        tr:hover {{
            background-color: {bg_primary};
        }}

        code {{
            background-color: {code_bg};
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 13px;
            color: {text_secondary};
        }}

        .info-block {{
            background-color: {bg_primary};
            border-left: 4px solid {accent_procedure};
            padding: 20px;
            border-radius: 4px;
        }}

        .info-block ul {{
            margin: 15px 0 0 0;
            padding-left: 25px;
        }}

        .info-block li {{
            margin-bottom: 8px;
        }}

        footer {{
            background-color: {bg_secondary};
            border-top: 2px solid {border_color};
            padding: 20px;
            text-align: center;
            margin-top: 40px;
            border-radius: 8px;
            color: {text_secondary};
            font-size: 13px;
        }}

        /* Responsive design */
        @media (max-width: 768px) {{
            .container {{
                padding: 15px;
            }}

            h1 {{
                font-size: 22px;
            }}

            h2 {{
                font-size: 18px;
            }}

            .meta-info {{
                flex-direction: column;
                gap: 10px;
            }}

            .node {{
                padding: 12px;
            }}

            table {{
                font-size: 12px;
            }}

            th, td {{
                padding: 8px;
            }}
        }}"#,
        bg_primary = colors.bg_primary,
        bg_secondary = colors.bg_secondary,
        text_primary = colors.text_primary,
        text_secondary = colors.text_secondary,
        border_color = colors.border_color,
        accent_procedure = colors.accent_procedure,
        accent_function = colors.accent_function,
        accent_variable = colors.accent_variable,
        accent_assignment = colors.accent_assignment,
        code_bg = colors.code_bg,
    )
}

/// Renders semantic nodes as HTML
fn render_nodes(nodes: &[bsl_shared::ir::SemanticNode], colors: &ColorScheme, _compact: bool) -> String {
    nodes
        .iter()
        .enumerate()
        .map(|(idx, node)| render_single_node(idx, node, colors))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Renders a single semantic node
fn render_single_node(
    _idx: usize,
    node: &bsl_shared::ir::SemanticNode,
    colors: &ColorScheme,
) -> String {
    let (class, emoji, kind) = match &node.kind {
        SemanticNodeKind::ProcedureDeclaration { name, params, .. } => (
            "node-procedure",
            "🔵",
            format!(
                "Procedure <span class=\"node-name\">{}</span> with {} parameters",
                escape_html(name),
                params.len()
            ),
        ),
        SemanticNodeKind::FunctionDeclaration {
            name,
            params,
            return_type,
            ..
        } => (
            "node-function",
            "⚙️",
            format!(
                "Function <span class=\"node-name\">{}</span> ({} params) → <span class=\"detail-value\">{}</span>",
                escape_html(name),
                params.len(),
                return_type.as_ref().map(|t| escape_html(t)).unwrap_or_else(|| "Void".to_string())
            ),
        ),
        SemanticNodeKind::VariableDeclaration {
            name,
            type_hint,
            ..
        } => (
            "node-variable",
            "📌",
            format!(
                "Variable <span class=\"node-name\">{}</span>: <span class=\"detail-value\">{}</span>",
                escape_html(name),
                type_hint.as_ref().map(|t| escape_html(t)).unwrap_or_else(|| "Unknown".to_string())
            ),
        ),
        SemanticNodeKind::Assignment {
            variable,
            value_type,
        } => (
            "node-assignment",
            "✏️",
            format!(
                "Assignment <span class=\"node-name\">{}</span> = <span class=\"detail-value\">{}</span>",
                escape_html(variable),
                escape_html(value_type)
            ),
        ),
        SemanticNodeKind::IfStatement { .. } => (
            "node-procedure",
            "🔀",
            "Conditional Statement (If...Then...Else...EndIf)".to_string(),
        ),
        SemanticNodeKind::WhileLoop { .. } => (
            "node-procedure",
            "🔄",
            "While Loop (While...Do...EndDo)".to_string(),
        ),
        SemanticNodeKind::ForLoop { variable, .. } => (
            "node-procedure",
            "🔁",
            format!("For Loop (For {} in ...)", escape_html(variable)),
        ),
        SemanticNodeKind::Return { value_type } => (
            "node-function",
            "↩️",
            format!(
                "Return Statement: <span class=\"detail-value\">{}</span>",
                value_type.as_ref().map(|t| escape_html(t)).unwrap_or_else(|| "Void".to_string())
            ),
        ),
        _ => (
            "node-variable",
            "❓",
            "Other Node".to_string(),
        ),
    };

    format!(
        r#"<div class="node {class}">
    <div class="node-header">
        <span class="node-kind">{emoji}</span>
        <span class="node-kind" style="background-color: {color}; color: white;">
            {kind_text}
        </span>
    </div>
    <div class="node-details">
        {kind}
    </div>
</div>"#,
        class = class,
        emoji = emoji,
        kind_text = match &node.kind {
            SemanticNodeKind::ProcedureDeclaration { .. } => "PROCEDURE",
            SemanticNodeKind::FunctionDeclaration { .. } => "FUNCTION",
            SemanticNodeKind::VariableDeclaration { .. } => "VARIABLE",
            SemanticNodeKind::Assignment { .. } => "ASSIGNMENT",
            SemanticNodeKind::IfStatement { .. } => "IF_STATEMENT",
            SemanticNodeKind::WhileLoop { .. } => "WHILE_LOOP",
            SemanticNodeKind::ForLoop { .. } => "FOR_LOOP",
            SemanticNodeKind::Return { .. } => "RETURN",
            _ => "OTHER",
        },
        kind = kind,
        color = match &node.kind {
            SemanticNodeKind::ProcedureDeclaration { .. } => colors.accent_procedure,
            SemanticNodeKind::FunctionDeclaration { .. } => colors.accent_function,
            SemanticNodeKind::VariableDeclaration { .. } => colors.accent_variable,
            SemanticNodeKind::Assignment { .. } => colors.accent_assignment,
            _ => colors.accent_procedure,
        },
    )
}

/// Renders symbol table as HTML table
fn render_symbol_table(symbols: &bsl_shared::ir::SymbolTable) -> String {
    // Count total symbols
    let total_functions = symbols.global_functions.len();
    let total_procedures = symbols.global_procedures.len();

    if total_functions == 0 && total_procedures == 0 {
        return "<div class=\"info-block\">No symbols in table</div>".to_string();
    }

    let mut table_rows = String::new();

    // Add functions
    for (name, sig) in &symbols.global_functions {
        let return_type = sig.return_type.as_ref().map(|t| escape_html(t))
            .unwrap_or_else(|| "void".to_string());

        table_rows.push_str(&format!(
            r#"<tr>
    <td><code>{}</code></td>
    <td>Function</td>
    <td><code>{}</code></td>
</tr>"#,
            escape_html(name),
            return_type
        ));
    }

    // Add procedures
    for name in symbols.global_procedures.keys() {
        table_rows.push_str(&format!(
            r#"<tr>
    <td><code>{}</code></td>
    <td>Procedure</td>
    <td><code>void</code></td>
</tr>"#,
            escape_html(name)
        ));
    }

    format!(
        r#"<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Kind</th>
            <th>Type</th>
        </tr>
    </thead>
    <tbody>
        {}
    </tbody>
</table>"#,
        table_rows
    )
}

/// Escapes HTML special characters
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use bsl_shared::ir::{SemanticProgram, SymbolTable};

    #[test]
    fn test_generate_dark_theme() {
        let program = SemanticProgram {
            symbols: SymbolTable::new(),
            nodes: vec![],
            source_info: bsl_shared::ir::SourceInfo { path: "test.bsl".to_string(), content_hash: 0 },
            cfg: None,
        };
        let html = generate_semantic_html(&program, "test.bsl", RenderOptions {
            theme: Theme::Dark,
            compact: false,
        });
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("bg-gray-900"));
        assert!(html.contains("Semantic Tree Visualization"));
    }

    #[test]
    fn test_generate_light_theme() {
        let program = SemanticProgram {
            symbols: SymbolTable::new(),
            nodes: vec![],
            source_info: bsl_shared::ir::SourceInfo { path: "test.bsl".to_string(), content_hash: 0 },
            cfg: None,
        };
        let html = generate_semantic_html(&program, "test.bsl", RenderOptions {
            theme: Theme::Light,
            compact: false,
        });
        assert!(html.contains("bg-white"));
        assert!(html.contains("Semantic Tree Visualization"));
    }

    #[test]
    fn test_html_escaping() {
        assert_eq!(escape_html("<script>"), "&lt;script&gt;");
        assert_eq!(escape_html("\"quoted\""), "&quot;quoted&quot;");
    }
}
